Update Hugo version in GitHub Actions workflow to fix build compatibility with Hextra theme

diff --git a/.github/workflows/pages.yaml b/.github/workflows/pages.yaml
--- a/.github/workflows/pages.yaml
+++ b/.github/workflows/pages.yaml
@@ -32,12 +32,12 @@ jobs:
   build:
     runs-on: ubuntu-latest
     env:
-      HUGO_VERSION: 0.128.0
+      HUGO_VERSION: 0.156.1
     steps:
       - name: Install Hugo CLI
         run: |
-          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
-          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
+          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb && \
+          ls ${{ runner.temp }} && sudo dpkg -i ${{ runner.temp }}/hugo.deb
       - name: Install Dart Sass
         run: sudo snap install dart-sass
       - name: Checkout
@@ -49,18 +49,31 @@ jobs:
         id: pages
         uses: actions/configure-pages@v4
       - name: Install Node.js dependencies
-        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
+        run: |
+          if [[ -f package-lock.json || -f npm-shrinkwrap.json ]]; then
+              npm ci
+          else
+              echo "No Node dependencies to install."
+          fi
       - name: Build with Hugo
         env:
           # For maximum backward compatibility with Hugo modules
           HUGO_ENVIRONMENT: production
           HUGO_ENV: production
         run: |
-          hugo mod tidy
+          hugo mod tidy && echo "Modules tidy operation complete." || echo "Modules tidy operation failed."
           hugo \
             --gc \
             --minify \
-            --baseURL "${{ steps.pages.outputs.base_url }}/"
+            --baseURL "${{ steps.pages.outputs.base_url }}/" && echo "Build success!" || echo "Build failed."
+      - name: Verify artifact directory
+        run: |
+          if [ -d ./public ]; then
+            echo "Artifacts ready for upload."
+          else
+            echo "Build failed. Artifacts not found."
+            exit 1
+          fi
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
